% Autogenerated by populate_scenarios.py on UTC-20210518-210133.

s = m.Species({m.Species.Name} == "CAS(c)");
assert(s.Units == "uM");
s.Value = 1;

s = m.Species({m.Species.Name} == "Ran·GTP(n)");
assert(s.Units == "uM");
s.Value = 3;

s = m.Species({m.Species.Name} == "NPC");
assert(s.Units == "uM");
s.Value = 0.5;

r = m.Reactions({m.Reactions.Name} == "hydrolysis1");
k = r.KineticLaw;
p = k.Parameters({k.Parameters.Name} == "kf");
assert(p.Units == "1/s");
p.Value = 0.1;

r = m.Reactions({m.Reactions.Name} == "hydrolysis2");
k = r.KineticLaw;
p = k.Parameters({k.Parameters.Name} == "kf");
assert(p.Units == "1/s");
p.Value = 0.1;

r = m.Reactions({m.Reactions.Name} == "CAS with Ran");
k = r.KineticLaw;
p = k.Parameters({k.Parameters.Name} == "kf");
assert(p.Units == "1/uM/s");
p.Value = 0.01;

r = m.Reactions({m.Reactions.Name} == "CAS with Ran");
k = r.KineticLaw;
p = k.Parameters({k.Parameters.Name} == "kr");
assert(p.Units == "1/s");
p.Value = 0.015;

r = m.Reactions({m.Reactions.Name} == "Complex CAS with NPC");
k = r.KineticLaw;
p = k.Parameters({k.Parameters.Name} == "kf");
assert(p.Units == "1/uM/s");
p.Value = 0.001;

r = m.Reactions({m.Reactions.Name} == "Complex CAS with NPC");
k = r.KineticLaw;
p = k.Parameters({k.Parameters.Name} == "kr");
assert(p.Units == "1/s");
p.Value = 0.0001;

r = m.Reactions({m.Reactions.Name} == "CAS with NPC");
k = r.KineticLaw;
p = k.Parameters({k.Parameters.Name} == "kf");
assert(p.Units == "1/uM/s");
p.Value = 0.001;

r = m.Reactions({m.Reactions.Name} == "CAS with NPC");
k = r.KineticLaw;
p = k.Parameters({k.Parameters.Name} == "kr");
assert(p.Units == "1/s");
p.Value = 0.001;

