# RA, 2021-05-18

# https://stackoverflow.com/questions/64570647/google-drive-api-python-service-account-example
# https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-py
# https://developers.google.com/sheets/api/quickstart/python

import itertools
import contextlib

import pandas as pd

from bugs import *
from twig import log
from tcga.utils import Now

from tenacity import retry, retry_if_exception, stop_after_attempt, RetryCallState, Future

from oauth2client.service_account import ServiceAccountCredentials
from googleapiclient.discovery import build

out_dir = unlist1(Path(__file__).resolve().parent.parent.glob("scenarios"))

SHEETS_ID = '1rr0lp6ByU1bENysPyk0qLXYwMEmwEN0BVQYw7H2Hp30'


def if_sheets_fails(retry_state: RetryCallState):
    assert isinstance(retry_state.outcome, Future)
    log.warning(f"Fetching sheet failed with exception `{retry_state.outcome.exception()}`.")
    log.warning(f"LOADING FROM DISK.")
    df = pd.read_table(unlist1(out_dir.glob("*.tsv")), dtype=str, na_filter=None)
    return df


@retry(retry=retry_if_exception(Exception), stop=stop_after_attempt(3), retry_error_callback=if_sheets_fails)
def load() -> pd.DataFrame:
    SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']
    KEY_FILE_LOCATION = 'nct1-20210518-24b395f048ea.json'

    creds = ServiceAccountCredentials.from_json_keyfile_name(KEY_FILE_LOCATION, SCOPES)

    range = 'Sheet1!A1:ZZ'

    service = build('sheets', 'v4', credentials=creds)

    # Call the Sheets API
    sheet = service.spreadsheets()
    result = sheet.values().get(spreadsheetId=SHEETS_ID, range=range).execute()

    df = pd.DataFrame(itertools.zip_longest(*result['values'], fillvalue='')).T

    df.columns = df.iloc[0]
    df = df.drop(index=0)

    return df


def print_scenario(df, c):
    log.info(f"Making scenario: {c}.")

    print(f'% Autogenerated by {relpath(__file__)} on {Now()}.')
    print(f'')

    for (i, n, p, u, v) in zip(df.Item, df.Name, df.Parameter, df.Units, df[c]):
        if (v == ""):
            v = 0

        if (i == ""):
            pass
        elif (i == "Reaction"):
            print(
                *[
                    f'r = m.Reactions({{m.Reactions.Name}} == "{n}");',
                    f'k = r.KineticLaw;',
                    f'p = k.Parameters({{k.Parameters.Name}} == "{p}");',
                    f'assert(p.Units == "{u}");',
                    f'p.Value = {v};',
                    f'',
                ],
                sep='\n'
            )
        elif (i == "Species"):
            assert (p == "Value")
            print(
                *[
                    f's = m.Species({{m.Species.Name}} == "{n}");',
                    f'assert(s.Units == "{u}");',
                    f's.Value = {v};',
                    f'',
                ],
                sep='\n'
            )
        else:
            log.warning(f"Unknown item: `{i}`.")


def make_scenarios(df: pd.DataFrame):
    for c in df.columns[6:]:
        if c:
            with (out_dir / f"{c}.m").open(mode='w') as fd:
                with contextlib.redirect_stdout(fd):
                    print_scenario(df, c)


def make_readme(df):
    df.to_csv(out_dir / "scenarios.tsv", sep='\t', index=False)

    with (out_dir / "readme.html").open(mode='w') as fd:
        with contextlib.redirect_stdout(fd):
            print(f"[Parameters](https://docs.google.com/spreadsheets/d/{SHEETS_ID}):")
            print()
            print()
            print(df.to_markdown(index=False))


def main():
    df = load()
    make_scenarios(df)
    make_readme(df)


if __name__ == '__main__':
    main()
